name: Playwright End-to-End Tests

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install app dependencies
      run: |
        cd app
        npm install

    - name: Start the app
      run: |
        cd app
        npm run dev &
    
    - name: Wait for app to be ready
      run: |
        sleep 10

    - name: Install Playwright
      run: |
        cd tests
        npm install playwright
        npx playwright install

    - name: Run Playwright tests
      run: |
        cd tests
        npx playwright test
